# Part 1 - Numpy

## 1. Introduction

### a) What is NumPy?
* Short for "Numerical Python," the foundational library for scientific computing.
* Fast: High-performance support for large, multi-dimensional arrays and matrices.
* Includes a vast library of mathematical functions.

### b) Why & When to Use NumPy
* Converting raw data (sequences, pixels, sensor readings) into numerical arrays is the essential first step for just about any computational pipeline.
* While Python lists are flexible, they are slow for math. NumPy uses **vectorization** to perform operations at near-C speeds (more on this later).
* NumPy arrays occupy significantly less RAM than Python lists by storing data as raw binary rather than expensive Python "objects."
* It is the "lingua franca" of Python data science.
  * Libraries like **Pandas** (table manipulation), **Scikit-Learn** (machine learning), and **Matplotlib** (visualization) are built directly on top of NumPy arrays.
  * Understanding of Numpy generalizes.
  * Large community, well-maintained.

### c) Reference material and further reading
* This module is largely based on the free [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html)
* [Numpy Documentation](https://numpy.org/doc/2.4/), in particular the ['the absolute basics for beginners' tutorial](https://numpy.org/doc/2.4/user/absolute_beginners.html) and ['learn' sections](https://numpy.org/learn/)

In [1]:
import numpy as np  # Importing the Numpy module, bind to the variable 'np' in the local scope

## 2. Numpy Data Types

*  In statically-typed languges (eg: C, Java), data types are explicitly declared. In Python, types are dynamically inferred, meaning a variable can point to any object type.
  * While flexible, this "object overhead" becomes costly when storing millions of values.
* A Python integer is more than just a number; it is a C structure containing:
  * Reference count (memory management)
  * Type code (identifies it as an integer)
  * Size
  * The value itself
* A Python list is a collection of pointers to these full Python objects. This allows a list to be heterogeneous (containing multiple types)

In [2]:
# A Python list with multiple types
L = [True, "2", 3.0, 4]
[type(item) for item in L]

[bool, str, float, int]

### NumPy Arrays

* NumPy arrays store data in a single contiguous block of memory. All elements must be of the same type, which eliminates the per-element overhead and allows for much faster computation.
  * It also provides efficiently implemented operations for the arrays
* If we are using very large arrays, we often 'pre-allocate' (create a placeholder) them for efficiency.
  * Avoid Expensive Resizing
  * Ensure the system reserves a single, unbroken block for your data
  * Verify immediately if your system has enough RAM for the task

In [10]:
# Creating NumPy Arrays from lists using 'np.array()'

# Creating an array from a list
a1 = np.array([1, 4, 2, 5, 3])

# If you provide a mixed-type input...Upcasting / type coersion occurs.
# Hierarchy: bool --> int --> float --> complex --> string
a2 = np.array([3.14, 4, 2, 3])  # e.g.: integers to floats

# Explicitly setting the data type (eg: bool_, int64, int32, etc...)
a3 = np.array([1, 2, 3, 4], dtype="float32")

# Unlike Python lists, NumPy arrays can explicitly be multi-dimensional
matrix = np.array([[2, 3, 4], [4, 5, 6], [6, 7, 8]])

print(a1)
print("\n", a2)
print("\n", a3)
print("\n", matrix)

[1 4 2 5 3]

 [3.14 4.   2.   3.  ]

 [1. 2. 3. 4.]

 [[2 3 4]
 [4 5 6]
 [6 7 8]]


In [11]:
# Pre-allocation functions: useful for initializing large arrays

# Create a length-10 integer array filled with zeros
zeros = np.zeros(10, dtype=int)
print("Zeros:\n", zeros)

# Create a 3x5 array filled with 3.14
full = np.full((3, 5), 3.14)
print("\nFull with 3.14:\n", full)

# Many types of pre-allocations beyond these.

Zeros:
 [0 0 0 0 0 0 0 0 0 0]

Full with 3.14:
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [12]:
# Many useful functions for generating ranges and for testing algorithms:

# Five values evenly spaced between 0 and 1
linspace_seq = np.linspace(0, 1, 5)
print("\nLinspace (0-1, 5 values):", linspace_seq)

# 3x3 array of uniformly distributed random values between [0.0, 1.0)
random_float = np.random.random((3, 3))
print("\nRandom Floats:\n", random_float)


Linspace (0-1, 5 values): [0.   0.25 0.5  0.75 1.  ]

Random Floats:
 [[0.42099368 0.28380382 0.9609779 ]
 [0.67293347 0.36003491 0.1400843 ]
 [0.13494161 0.72064294 0.20243477]]


## 3. NumPy Array Basics

In [14]:
# Arrays for the following examples
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

### a) Attributes

* Properties that provide information about the array without modifying the data
* There are numerous attributes, as in all the following sections, we will just see a couple of frequently useful ones

In [16]:
# Create a 3D array

print("x3: \n", x3)
print("\nx3 ndim: ", x3.ndim)  # Number of dimensions
print("x3 shape:", x3.shape)  # Size of each dimension
print("x3 size: ", x3.size)  # Total number of elements
print("dtype:   ", x3.dtype)  # Data type of elements

x3: 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


### b) Indexing and Slicing
* NumPy uses standard Python indexing but extends it to multiple dimensions using commas.
* Access subarrays with the slice notation, marked by the colon (:) character.
  * x[start:stop:step]

In [30]:
# 1D example

print("x1: \n", x1)
print("\n", x1[0])
print("\n", x1[-1])

# 2D example, accessing elements: [row, column]
print("\n x2: \n", x2)
print("\nElement at [0, 0]:", x2[0, 0])

# 3D example - Get the value in the 1st layer, 3rd row, 5th column
print("\n x3: \n", x3)
print("\nElement at [0, 2, 4]:", x3[0, 2, 4])

x1: 
 [999   0   3   3   7   9]

 999

 9

 x2: 
 [[999   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]

Element at [0, 0]: 999

 x3: 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]

Element at [0, 2, 4]: 8


In [19]:
# Slicing 1D

x = np.arange(10)
print("Full array:", x)
print("First five:", x[:5])
print("Elements after index five:", x[5:])
print("Every other:", x[::2])

Full array: [0 1 2 3 4 5 6 7 8 9]
First five: [0 1 2 3 4]
Elements after index five: [5 6 7 8 9]
Every other: [0 2 4 6 8]


In [20]:
# Multi-dimensional slicing - [rows_slice, columns_slice]

print("\n Full array: \n", x2)
print("\n first column of x2: \n", x2[:, 0])
print("\n First 2 rows, first 3 columns:\n", x2[:2, :3])
print("\n All rows, every other column: \n", x2[:3, ::2])


 Full array: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

 first column of x2: 
 [3 7 1]

 First 2 rows, first 3 columns:
 [[3 5 2]
 [7 6 8]]

 All rows, every other column: 
 [[3 2]
 [7 8]
 [1 7]]


In [21]:
# Values can also be modified using any of the familiar Python index notation

print("\n Full array: \n", x1)
x1[0] = 999
print("\n Modified array: \n", x1)

print("\n Full array: \n", x2)
x2[0, 0] = 999
print("\n Modified array: \n", x2)

# Note this returns a view, the original obejct is modified...


 Full array: 
 [5 0 3 3 7 9]

 Modified array: 
 [999   0   3   3   7   9]

 Full array: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

 Modified array: 
 [[999   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


### c) Copying aka views vs copies
* Numpy array slices return views rather than copies of the array data (Python list slices, in contrast, return copies)
* If we modify a subarray, we'll see that the original array is changed!
  * * If we don't want this behaviour to happen, use a deep copy!
* Copy: Owns its data. It is a completely separate object in memory. Changes to the copy do not affect the original data.
* View: Does not own the data, it points to the original memory. Changes to the view affect the original array (and vice versa).
* Useful, but can be confusing if not properly understood.
  * Why useful? When working with large datasets, we can access and process pieces of these datasets without the need to copy the ENTIRE underlying data buffer.

![img](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxIKA5FaIULwt2z18vPMBSD_HZ9PqakiPi8w&s)

In [ ]:
x2 = np.ones((3, 4))
print(x2)

x2_sub = x2[:2, :2]  # Made a subarray
print("\n", x2_sub)

x2_sub[0, 0] = 99  # Modified our subarray
print("\n", x2_sub)

# If we modify a subarray, we'll see that the original array is changed!
print("\n", x2)

In [ ]:
# If we don't want this to happen, use the a deep copy with '.copy()'
# Explicitly copies the data within an array or a subarray

x2 = np.ones((3, 4))
print(x2)

x2_sub_copy = x2[:2, :2].copy()  # Made a deep copy
print(x2_sub_copy)

x2_sub_copy[0, 0] = 99  # Modified the copy
print("\n", x2_sub_copy)

print("\n Intact original: \n", x2)

### d) Joining

In [ ]:
# Joining

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])

# Concatenate along the first axis (default axis = 0)
print("\n", np.concatenate([x, y]))
print("\n", np.concatenate([x, y, z]))

# For working with arrays of mixed dimensions, often clearer to use the np.vstack and np.hstack:
h = np.array([[99], [99]])
grid = np.array([[9, 8, 7], [6, 5, 4]])
print("\n Vertical Stack:\n", np.vstack([x, grid]))  # Vertical stack (rows)
print("\nHorizontal Stack:\n", np.hstack([grid, h]))  # Horizontal stack (columns)

## 4. Universal Functions
* Computation on NumPy arrays can be very fast...Or not.
* For speed, use vectorized operations, generally implemented through NumPy's universal functions
* Due to being dynamically typed, when you run a loop, Python interpreter must check the type of every single object in every iteration, which is incredibly slow.
* Vectorization = performing mathematical or logical operations on entire arrays at once, rather than iterating through individual elements using explicit Python loops
  * Unary (1 input) operations perform a specific calculation on each element of array independently. 
  * Binary (2 inputs) operations on arrays of the same size are performed on an element-by-element basis. Eg: A * B multiplies values at the same indices.
* On an array of 1 million elements, the 'vectorized' operation can be hundreds of times faster because it pushes the loop into the compiled C layer (leverages contiguous memory and data parallelization).

In [26]:
import numpy as np
import time

# Seed for reproducibility
np.random.seed(42)


def compute_squares(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] ** 2
    return output


# Large test array (1 million integers)
arr = np.random.randint(1, 100, size=1000000)

# Slow (Python for-loop)
start = time.time()
slow = compute_squares(arr)
t_slow = time.time() - start

# Fast (NumPy Vectorization)
start = time.time()
fast = arr**2
t_fast = time.time() - start

# Results
print(f"Outputs equal: {np.allclose(slow, fast)}")
print(f"Loop time:      {t_slow:.4f}s")
print(f"Vectorized time: {t_fast:.4f}s")
print(f"Speedup:        {t_slow / t_fast:.1f}x")

Outputs equal: True
Loop time:      0.3492s
Vectorized time: 0.0010s
Speedup:        346.2x


### Common Arithmetic Ufuncs
* NumPy maps standard arithmetic operators used on Numpy arrays to specific ufuncs.
* NumPy provides nearly every mathematical function you might need.
  * Too many to show here, check the documentation.
  * Scipy module 'scipy.special' offers a staggering amount of very niche Ufuncs.

In [28]:
x = np.arange(4)
print("x      =", x)
print("x + 5  =", x + 5)  # np.add(x, 5)
print("x * 2  =", x * 2)  # np.multiply(x, 2)
print("x ** 2 =", x**2)  # np.power(x, 2)
print("x % 2  =", x % 2)  # np.mod(x, 2)
print("sin(x) =", np.sin(x))

# These can be strung together however you wish. They follow the standard order of operations:
print(-((0.5 * x + 1) ** 2))

x      = [0 1 2 3]
x + 5  = [5 6 7 8]
x * 2  = [0 2 4 6]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]
sin(x) = [0.         0.84147098 0.90929743 0.14112001]
[-1.   -2.25 -4.   -6.25]


## 5. Aggregations
* Summary statistics for the data
* Reduce an array of values into a single summary statistic (like mean, sum, or standard deviation).
* Once again, far too many to cover here. Look in the docs and you will probably find what you need.

In [ ]:
big_array = np.random.rand(1000000)

print("Min:", big_array.min())
print("Max:", big_array.max())
print("Sum:", big_array.sum())
print("Mean:", big_array.mean())
print("Std:", big_array.std())

In [ ]:
# Multi-Dimensional Aggregates
# Can operate along a specific axis

M = np.random.random((3, 4))
print("Matrix:\n", M)

# Sum of the entire matrix
print("\nTotal sum:", M.sum())

# Minimum value of each column (axis 0)
print("Min of each column:", M.min(axis=0))

# Maximum value of each row (axis 1)
print("Max of each row:", M.max(axis=1))

In [31]:
# 'Real world' tip: we often encounter missing values represented as NaN (Not a Number).
# Standard aggregates will return NaN if even one NaN is present.
# NumPy provides "NaN-safe" versions that ignore these values.

data = np.array([1, 2, np.nan, 4, 5])

print("Standard sum:", np.sum(data))  # Returns nan
print("NaN-safe sum:", np.nansum(data))  # Returns 12.0

Standard sum: nan
NaN-safe sum: 12.0


## 6. Manual Reshaping and Dimension Manipulation
* Allows you to change the structure of an array without changing its data.
* For 'reshape' to work, the size of the initial array must match the size of the reshaped array.
  * Creates a view where possible.
  * In some cases where the array becomes non-contiguous (perhaps after a ndarray.transpose operation), the reshaping cannot be done by modifying strides and requires a copy. 

In [ ]:
# Reshape 1-9 into a 3x3 grid
grid = np.arange(1, 10)
print("1x9 Grid:\n", grid)
print("3x3 Grid:\n", grid.reshape((3, 3)))

## 6. Broadcasting
* Another means of vectorizing operations is to use NumPy's broadcasting functionality.
* What if we want to apply ufuncs to two arrays of different sizes? Element-wise operations don't work.
* Broadcasting = Set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on arrays of different sizes.

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

**Rule 1:** If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

**Rule 2:** If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

**Rule 3:** If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

* In the image: the light boxes represent the broadcasted values:
  * Note: extra memory is not actually allocated in the course of the operation, but it can be useful conceptually to imagine that it is.

![BC](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [ ]:
# Example: Scalar and Array

a = np.arange(3)
print("Array + Scalar:", a + 5)

# We can think of this as an operation that stretches or duplicates
# the value 5 into the array [5, 5, 5], and adds the results.

In [ ]:
# Example: 1D Array and 2D Array

M = np.ones((3, 3))
a = np.arange(3)

print("\nMatrix M:\n", M)
print("M + a:\n", M + a)

# 'a' is stretched, or broadcast, across the second dim of M to match its shape.

In [ ]:
# Example: 3x1 + 1x3
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

print("a: \n", a)
print("Shape of a:", a.shape)  # (3, 1)
print("b: \n", b)
print("Shape of b:", b.shape)  # (3,) -> padded to (1, 3)

# Both are stretched to (3, 3)
print("\na + b:\n", a + b)

In [41]:
# If shapes are incompatible and neither has a dimension of 1, NumPy will throw a ValueError.

M = np.ones((3, 2))
a = np.arange(3)

print("M: \n", M)
print("\n M shape:", M.shape)
print("a: \n", a)
print("\n M shape:", a.shape)

try:
    print(M + a)
except ValueError as e:
    print("\n Error:", e)

# Note: To fix this, you would usually need to reshape a to (3, 1)
#  using a[:, np.newaxis] to make it compatible with Rule 2.
# np.newaxis is a constant --> 1D array will become 2D array, 2D array will become 3D array, etc...

result = M + a[:, np.newaxis]

print("\n a with newaxis: \n", a[:, np.newaxis])
print("a shape with newaxis:", a[:, np.newaxis].shape)
print("\nResult:\n", result)

M: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

 M shape: (3, 2)
a: 
 [0 1 2]

 M shape: (3,)

 Error: operands could not be broadcast together with shapes (3,2) (3,) 

 a with newaxis: 
 [[0]
 [1]
 [2]]
a shape with newaxis: (3, 1)

Result:
 [[1. 1.]
 [2. 2.]
 [3. 3.]]


## 7. Boolean Masking
* Just like arithmetic, comparison operators in NumPy are vectorized. They return a Boolean array where each element is True or False.

In [32]:
x = np.array([1, 2, 3, 4, 5])

# Some element-wise logic examples
print("x < 3: ", x < 3)  # less than
print("x == 3:", x == 3)  # equal
print("x != 3:", x != 3)  # not equal

# It is also possible to do an element-wise comparison of two arrays, and to include compound expressions:

print("\n (2 * x) == (x ** 2): ", (2 * x) == (x**2))

x < 3:  [ True  True False False False]
x == 3: [False False  True False False]
x != 3: [ True  True False  True  True]

 (2 * x) == (x ** 2):  [False  True False False False]

Matrix M:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]

M Values < 6:
 [[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In [34]:
# To combine conditions, use bitwise operators (&, |, ^, ~) = (And, Or, Xor, Not)
# Note: You must use parentheses because of operator precedence.

# Eg: we want Values between 0.5 and 1.0

x = np.arange(10)
print("Between 3 and 8:", (x > 3) & (x < 8))

# Note we must use bitwise operators:
#    - and / or: Checks if the entire object is True or False. Using these on an array will cause an error
#    - & / |: Checks every individual bit or element. This is what you want for NumPy arrays.

Between 3 and 8: [False False False False  True  True  True  True False False]


In [ ]:
# Masking is arguably the most powerful use case.
# You can use a Boolean array as an index to extract the actual values that meet a condition.

M = np.array([[5, 0, 3, 3], [7, 9, 3, 5], [2, 4, 7, 6]])

# Masking: Select values less than 5
print("Values < 5:", M[M < 5])

# Example: Statistics on filtered data
rainy = M[M > 0]
print("Average of non-zero values:", np.mean(rainy))