# Slow Python data structures

## Lists and loops

__List__ and __dictionaries__ are the main Python data structures. 

This is a list:

In [1]:
numbers = [1, 2, 3, 4, 5]

Lists are accessed by index:

In [2]:
numbers[2]

3

This is a dictionary:

In [3]:
dictio = {"name": "Jin", "age": 42}

Dictionaries are accessed by key:

In [4]:
dictio["name"]

'Jin'

Lists and dictionaries are often manipulated with for loops:

In [5]:
def create_numbers(n_values):
    numbers = []
    for x in range(n_values):
        numbers += [1 + x]
    return numbers

In [6]:
numbers = create_numbers(1000)
numbers

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [7]:
inverses = []
for x in numbers:
    inverses += [1 / x]

## Optimizing for loops

Python loops are slow:

In [8]:
%%timeit
inverses = []
for x in numbers:
    inverses += [1 / x]

110 µs ± 13.7 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


List comprehensions reduce the Python interpreter overhead:


In [9]:
%%timeit
inverses_comp = [1 / x for x in numbers]

45.7 µs ± 2.35 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Built-in function `map` returns an iterator that mimics the for loop:

In [10]:
%%timeit
n = map(lambda x: 1 / x, numbers)

168 ns ± 5.98 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [11]:
n = map(lambda x: 1 / x, numbers)

In [12]:
%%timeit
list(n)

136 ns ± 2.42 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


## Quiz
    
<div class="alert alert-block alert-warning">
Does the following statement raise an error?

<PRE>
a = map(lambda x: 1/x, [0])
</PRE>
 
&#x25a2; Yes
    
&#x25a2; No
</div>

In [13]:
a = map(lambda x: 1 / x, [0])

Answer: no it doesn't! But this one does:

In [14]:
# list(a)

# Fast NumPy arrays

## NumPy overview
NumPy arrays are the "workhorse" of data analysis. They are omnipresent in data science.

A NumPy array can be created in various ways, including from a Python list:

In [15]:
import numpy as np

numbers_np = np.array(numbers)
numbers_np

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

NumPy provides a number of __vectorized__ functions that apply to arrays, such as:

In [16]:
# basic arithmetic
numbers_np + 1

array([   2,    3,    4,    5,    6,    7,    8,    9,   10,   11,   12,
         13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
         24,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
         35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
         46,   47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
         57,   58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
         68,   69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
         79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
         90,   91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
        101,  102,  103,  104,  105,  106,  107,  108,  109,  110,  111,
        112,  113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
        123,  124,  125,  126,  127,  128,  129,  130,  131,  132,  133,
        134,  135,  136,  137,  138,  139,  140,  141,  142,  143,  144,
        145,  146,  147,  148,  149,  150,  151,  1

In [17]:
# Mathematical functions
np.sqrt(numbers_np)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
        3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
        4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
        5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558,
        5.56776436,  5.65685425,  5.74456265,  5.83095189,  5.91607978,
        6.        ,  6.08276253,  6.164414  ,  6.244998  ,  6.32455532,
        6.40312424,  6.4807407 ,  6.55743852,  6.63324958,  6.70820393,
        6.78232998,  6.8556546 ,  6.92820323,  7.        ,  7.07106781,
        7.14142843,  7.21110255,  7.28010989,  7.34846923,  7.41619849,
        7.48331477,  7.54983444,  7.61577311,  7.68114575,  7.74596669,
        7.81024968,  7.87400787,  7.93725393,  8.        ,  8.06225775,
        8.1240384 ,  8.18535277,  8.24621125,  8.30662386,  8.36

In [18]:
# sum, count, min, max, etc
np.sum(numbers_np)

500500

## NumPy is fast

What's the fastest implementation to inverse a collection of numbers?

<div class="alert alert-block alert-warning">

&#x25a2; Python for loop on list:
<PRE>inverses = []
for x in numbers:
    inverses += [ 1/x ]
</PRE>

&#x25a2; Python map iterator:
<PRE>
map(lambda x: 1/x, numbers)
</PRE>
     
&#x25a2; NumPy vectorized operation:
<PRE>
1/numbers_np
</PRE>

</div>

NumPy arrays are implemented in C which makes them faster than Python lists:

In [19]:
%%timeit
1 / numbers_np

3.34 µs ± 260 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


That's 20x faster than the initial for loop!

In [20]:
%%timeit
inverses = []
for x in numbers:
    inverses += [1 / x]

93.8 µs ± 2.19 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


And also faster than a map iteration:

In [21]:
%%timeit
list(map(lambda x: 1 / x, numbers))

79 µs ± 2.65 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Other NumPy functions also provide similar speed-ups compared to list operations:

In [22]:
%%timeit
s = 0
for x in numbers:
    s += x
s

43.5 µs ± 524 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [23]:
%%timeit
np.sum(numbers_np)

4.23 µs ± 145 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
import math

In [25]:
%%timeit
numbers_log = []
for x in numbers:
    numbers_log += [math.log(1 + x)]

237 µs ± 19.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [26]:
%%timeit
numbers_log_comp = [math.log(1 + x) for x in numbers]

159 µs ± 4.58 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [27]:
%%timeit
numbers_log_comp = map(lambda x: math.log(1 + x), numbers)

168 ns ± 6.83 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


# Additional resources

More resources on Python code optimization:
* https://www.guru99.com/python-map-function.html
* https://jakevdp.github.io/PythonDataScienceHandbook/02.03-computation-on-arrays-ufuncs.html